export const DashboardPageElements = {

  dashboardURL:'/dashboard',
  welcomeHeading:'//h1[contains(@class,"font-heading") and contains(.,"Welcome back")]',
  welcomeSubtext:'//p[contains(.,"Your music. Your moments.")]',
  songAILogoMobile:'//a[@href="/dashboard"][contains(.,"SongAI")]',
  songAILogoSidebar:'//aside//a[@href="/dashboard"][contains(.,"SongAI")]',
  searchBtn:'//button[contains(.,"Search Songs")]',
  createLabel:'//aside//p[text()="Create"]',
  createNewSongSidebar:'//aside//button[contains(.,"Create a New Song")]',
  yourMusicLabel:'//p[contains(.,"Your Music")]',
  yourLatestSongBtn:'//button[contains(.,"Your Latest Song")]',
  yourSongsBtn:'//button[contains(.,"Your Songs")]',
  giftingLabel:'//p[contains(.,"Gifting")]',
  sendASongLink:'//a[@href="/checkout?from=dashboard"][contains(.,"Send a Song")]',
  yourGiftsLink:'//a[contains(.,"Your Gifts")]',
  planCard:'//div[contains(.,"Essential Plan")]',
  planName:'//span[contains(.,"Essential Plan")]',
  planSongsRemaining:'//div[contains(@class,"text-[11px]") and contains(.,"songs remaining this month")]',
  upgradePlanLink:'//a[@href="/pricing"][contains(.,"Upgrade Plan")]',
  userAvatar:'//div[contains(@class,"rounded-full")][contains(@class,"font-bold")]',
  userNameDisplay:'//p[contains(@class,"font-medium") and contains(@class,"text-white") and contains(@class,"truncate")]',
  userEmailDisplay:'//p[contains(@class,"text-text-muted") and contains(@class,"truncate") and contains(@class,"text-[11px]")]',
  logoutBtn:'//button[contains(@class,"font-body") and contains(.,"Log out")]',
  createNewSongCard:'//main//button[contains(.,"Create a New Song")]',
  createNewSongCardText:'//span[contains(.,"Gift someone special")]',
  noSongsMessage:'//p[contains(.,"No songs yet")]',
  settingsBtn:'//button[contains(.,"Settings")]',
  myAccountOption:'//button[contains(.,"My Account")] | //a[contains(.,"My Account")]',
  billingOption:'//a[contains(.,"Billing")] | //button[contains(.,"Billing")]',
  ordersOption:'//a[contains(.,"Orders")] | //button[contains(.,"Orders")]',
  notificationsOption:'//a[contains(.,"Notifications")] | //button[contains(.,"Notifications")]',
  privacyOption:'//a[contains(.,"Privacy")] | //button[contains(.,"Privacy")]',
  supportOption:'//a[contains(.,"Customer Support")] | //button[contains(.,"Customer Support")]',
  aiHelpBtn:'//button[contains(.,"AI Help")]',
  backToDashboardLink:'//a[contains(.,"Back to dashboard")]',
  myAccountHeading:'//h1[contains(.,"My account")]',
  billingHeading:'//h1[contains(.,"Billing")]',
  billingPaymentHistory:'//h2[contains(.,"Payment history")]',
  billingPaymentMethod:'//h2[contains(.,"Payment method")]',
  ordersHeading:'//h1[contains(.,"Orders")]',
  ordersEmptyMessage:'//p[contains(.,"You don\'t have any orders yet")]',
  notificationsHeading:'//h1[contains(.,"Notifications")]',
  notificationsSaveBtn:'//button[contains(translate(.,"ABCDEFGHIJKLMNOPQRSTUVWXYZ","abcdefghijklmnopqrstuvwxyz"),"save preferences")]',
  notificationsResetBtn:'//button[contains(.,"Reset to defaults")]',
  privacyHeading:'//h1[contains(.,"Privacy")]',
  privacyDataWeStore:'//h2[text()="Data we store"]',
  privacyExportData:'//h3[contains(.,"Export your data")]',
  privacyDeleteAccount:'//h3[contains(.,"Delete account")]',
  supportHeading:'//h1[contains(.,"Customer support")]',
  supportContactForm:'//a[@href="/contact"][contains(.,"Contact form")]',
  supportCommonQuestions:'//h2[text()="Common questions"]',

};
