export const LandingPageElements = {

  navOccasion: '(//a[text()="Occasions"])[1]',
  navWorking: '(//a[text()="How It Works"])[1]',
  navGiftCards: '(//a[text()="Pricing"])[1]',
  navLogin: '//a[text()="FAQ"]',
  navHearSongs: '//nav//a[@href="#occasions"]',
  navLogo: '//a[@href="/"]/span[contains(@class,"font-bold")]',
  navSignIn: '//nav//a[@href="/auth/login"]',
  navCreateSongCTA: '//nav//a[@href="/create"][contains(@class,"bg-white")]',
  navHamburger: '//nav//button[@aria-label="Toggle menu"]',

  videoModalCloseBtn: '//button[contains(@class,"absolute")][.//*[contains(@class,"lucide-x")]]',

  heroBadge: '//div[contains(@class,"rounded-full")][contains(.,"Personalised song gifts")]',
  heroHeadline: '//h1[contains(.,"Say it in a way")]',
  heroBodyCopy: '//p[contains(.,"Turn memories, milestones")]',
  heroBgImage: '//section[@style[contains(.,"#0a0633")]]//img[@alt=""]',
  heroMascot: '//img[@alt="SongAI mascot"]',

  heroInput: '//input[@placeholder="Who\'s this song for?"]',
  heroCreateBtn: '//button[contains(.,"Create Your Song")]',
  heroWatchLink: '//button[contains(.,"Watch Explainer")]',

  songCardsHeading: '//h2[contains(.,"Real stories, turned into real songs")]',
  songCardsTapLabel: '//p[contains(.,"Tap any song to listen")]',
  songCardFirst: '(//div[contains(@class,"group shrink-0")])[1]',
  songCardFirstImage: '(//div[contains(@class,"group shrink-0")]//img)[1]',
  songCardFirstTitle: '(//div[contains(@class,"group shrink-0")]//h3)[1]',
  songCardFirstArtist: '(//div[contains(@class,"group shrink-0")]//p[contains(@class,"text-white/70")])[1]',
  songCardPlayBtn: '(//div[contains(@class,"group shrink-0")]//button)[1]',

  howItWorksEyebrow: '//section[@id="how-it-works"]//p[contains(.,"Simple. Fast. Personal.")]',
  howItWorksHeading: '//section[@id="how-it-works"]//h2[contains(.,"How your story becomes a song")]',
  howItWorksSubcopy: '//section[@id="how-it-works"]//p[contains(.,"From a few simple words")]',
  howItWorksNoBold: '//section[@id="how-it-works"]//span[contains(@class,"font-bold")][contains(.,"No music experience needed")]',
  howStep01Circle: '(//section[@id="how-it-works"]//div[contains(@class,"rounded-full")])[1]',
  howStep02Circle: '(//section[@id="how-it-works"]//div[contains(@class,"rounded-full")])[2]',
  howStep03Circle: '(//section[@id="how-it-works"]//div[contains(@class,"rounded-full")])[3]',
  howStep04Circle: '(//section[@id="how-it-works"]//div[contains(@class,"rounded-full")])[4]',
  howConnectorLine: '//section[@id="how-it-works"]//div[contains(@style,"linear-gradient")][contains(@style,"scaleX")]',
  howStep01Title: '(//section[@id="how-it-works"]//h3[contains(.,"Tell us the story")])[1]',
  howStep01Desc: '(//section[@id="how-it-works"]//h3[contains(.,"Tell us the story")]/following-sibling::p)[1]',
  howStep02Title: '(//section[@id="how-it-works"]//h3[contains(.,"We turn it into a song")])[1]',
  howStep02Desc: '(//section[@id="how-it-works"]//h3[contains(.,"We turn it into a song")]/following-sibling::p)[1]',
  howStep03Title: '(//section[@id="how-it-works"]//h3[contains(.,"Listen and reshape it")])[1]',
  howStep03Desc: '(//section[@id="how-it-works"]//h3[contains(.,"Listen and reshape it")]/following-sibling::p)[1]',
  howStep04Title: '(//section[@id="how-it-works"]//h3[contains(.,"Gift it or keep it")])[1]',
  howStep04Desc: '(//section[@id="how-it-works"]//h3[contains(.,"Gift it or keep it")]/following-sibling::p)[1]',

  sayItEyebrow: '(//p[contains(.,"It starts with a sentence")])[1]',
  sayItHeading: '//h2[contains(.,"Say it your way")]',

  audioSectionHeading: '//h2[contains(.,"Real songs. Real emotion.")]',
  audioPlayerCard: '//div[contains(@class,"rounded-xl")][.//p[contains(@class,"text-[14px]") and contains(@class,"truncate")]]',
  audioAlbumArt: '//img[@alt="Our Italian Summer album art"]',
  audioSongTitle: '//p[contains(@class,"text-[14px]") and contains(@class,"truncate") and contains(@class,"text-white")]',
  audioArtistOccasion: '//p[contains(.,"Sarah & James")][contains(.,"Anniversary")]',
  audioPlayBtn: '(//div[contains(@class,"w-8 h-8")]//svg[contains(@class,"lucide-play")])[1]',
  audioLikeIcon: '//svg[contains(@class,"lucide-heart")]',
  audioShareIcon: '//svg[contains(@class,"lucide-share")]',
  audioDownloadIcon: '//svg[contains(@class,"lucide-download")]',

  giftEyebrow: '//p[contains(.,"The gift")]',
  giftHeading: '//h2[contains(.,"The most personal gift")]',
  giftBodyCopy: '//p[contains(.,"Each song comes with a beautiful shareable page")]',

  giftPkgHeading: '//h2[contains(.,"Everything they\'ll receive")]',
  giftPkgMainImage: '//div[contains(@class,"col-span-2")]//img[@alt="Original Song"]',
  giftPkgOriginalLabel: '//p[contains(.,"Original Song")][contains(@class,"text-electric")]',
  giftPkgAlbumCard: '//img[@alt="Album Artwork"]/ancestor::div[contains(@class,"rounded-2xl")]',
  giftPkgAlbumLabel: '//p[contains(.,"Album Artwork")][contains(@class,"text-violet")]',
  giftPkgAlbumDesc: '//p[contains(.,"Custom cover art")]',
  giftPkgVideoCard: '//p[contains(.,"Video Canvas")]/ancestor::div[contains(@class,"rounded-2xl")]',
  giftPkgVideoLabel: '//p[contains(.,"Video Canvas")]',

  testimonialsEyebrow: '//p[contains(.,"Real People. Real Stories.")]',
  testimonialsHeading: '//h2[contains(.,"Most gifts are forgotten")]',
  testimonialsMainText: '//p[contains(@class,"leading-[1.8]") and contains(@class,"mb-6") and contains(.,"know what to get David")]',
  testimonialsWaveform: '(//div[contains(@class,"flex items-end gap")])[1]',
  testimonialsTheSong: '(//p[contains(.,"The song")])[2]',
  testimonialsAnniversary: '//span[contains(.,"Anniversary")][ancestor::div[contains(@class,"bg-surface border")]]',
  testimonialsGraduation: '//span[contains(.,"Graduation")][ancestor::div[contains(@class,"bg-surface border")]]',
  testimonialsMemorial: '//span[contains(.,"Memorial")][ancestor::div[contains(@class,"bg-surface border")]]',

  pricingHeading: '//section[@id="pricing"]//h2[contains(.,"One song says it all")]',
  pricingMostPopular: '//div[contains(.,"Most Popular")][contains(@class,"rounded-full")]',
  plan1Title: '//h3[contains(.,"One Song Gift")]',
  plan1Price: '//h3[contains(.,"One Song Gift")]/ancestor::div[contains(@class,"rounded-2xl")]//span[contains(@class,"text-[36px]")]',
  plan2Title: '//h3[contains(.,"The VIP Experience")]',
  plan2CTA: '//a[@href="/create"][contains(.,"The VIP Experience")]',
  plan3Title: '//h3[contains(.,"Make It a Habit")]',
  plan3CTA: '//a[@href="/pricing"][contains(.,"Start Creating")]',

  faqHeading: '//h2[contains(.,"Before you gift")]',
  faqQuestion1: '//button[contains(.,"How does it work?")]',
  faqQuestion2: '//button[contains(.,"Can I listen before I buy?")]',
  faqQuestion3: '//button[contains(.,"What do I get when I gift a song?")]',
  faqQuestion4: '//button[contains(.,"What genres and styles are available?")]',
  faqQuestion5: '//button[contains(.,"Can I regenerate or change my song?")]',
  faqQuestion6: '//button[contains(.,"Is there an option for commercial release?")]',
  faqExpandIcon: '(//button[contains(@class,"w-full flex items-center")]//svg[contains(@class,"lucide-plus")])[1]',

};
